Repository oktrifianto/switching-login-register-js, pull requests merged in 2020-10, with the labels that each got.

#1 Adding New CSS File
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted

#2 Adding New JavaScript File
  index.html
  main.js
Labels: hacktoberfest-accepted, help wanted

#3 update padding top 1px
  style.css
Labels: hacktoberfest-accepted

#4 Update p style
  style.css
Labels: enhancement, hacktoberfest-accepted

#5 add pagination section on body
  index.html
  main.js
  style.css
Labels: hacktoberfest-accepted
